AWSTemplateFormatVersion: 2010-09-09
Description: >-
  crypto-bot-commander

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  LogLevelParameter:
    Type: String
    Description: Functions log level
    Default: info
    AllowedValues:
      - debug
      - info
  EnvironmentParameter:
    Type: String
    Description: Environment where the stack is deployed
    Default: test
    AllowedValues:
      - test
      - prod
  TracingParameter:
    Description: Boolean to enable or disable tracing
    Type: String
    Default: false
  ExchangesSecretNameParameter:
    Description: Name of the exchanges secret stored in Secrets Manager
    Type: String
  ExchangesSecretEncryptionKeyParameter:
    Description: Encryption key used to encrypt the exchanges secret in Secrets Manager (either a key id 'key/xxx' or an alias 'alias/xxx')
    Type: String
    Default: alias/aws/secretsmanager

Conditions:
  TracingCondition: !Equals [ !Ref TracingParameter, true ]

Mappings:
  EnvironmentMap:
    test:
      AvailableSymbols: BNB#BUSD,BTC#BUSD
      TriggerAllCandlesticksSchedule: rate(1 minute)
    prod:
      AvailableSymbols: BNB#BUSD,BTC#BUSD,XRP#BUSD
      TriggerAllCandlesticksSchedule: rate(1 minute)

Globals:
  Api:
    EndpointConfiguration:
      Type: EDGE
    OpenApiVersion: 3.0.3
    TracingEnabled: !Ref TracingParameter
  Function:
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 10
    AutoPublishAlias: Live
    Tracing: !If [ TracingCondition, Active, PassThrough ]
    Environment:
      Variables:
        LOG_LEVEL: !Ref LogLevelParameter
        ENV: !Ref EnvironmentParameter
        REGION: !Ref AWS::Region
        TRACING: !Ref TracingParameter

Resources:
  InitializeAllCandlesticksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Initialize all candlesticks function
      CodeUri: dist/webpack/initialize-all-candlesticks-handler
      Handler: app.handler
      Timeout: 300
      ReservedConcurrentExecutions: 1
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Environment:
        Variables:
          EXCHANGES_SECRET_NAME: !Ref ExchangesSecretNameParameter
          CANDLESTICK_TABLE_NAME: !Ref CandlestickTable
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${ExchangesSecretNameParameter}*
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${ExchangesSecretEncryptionKeyParameter}
        - DynamoDBWritePolicy:
            TableName: !Ref CandlestickTable

  TriggerAllCandlesticksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Trigger all candlesticks function
      CodeUri: dist/webpack/trigger-all-candlesticks-handler
      Handler: app.handler
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Environment:
        Variables:
          AVAILABLE_SYMBOLS: !FindInMap [ EnvironmentMap, !Ref EnvironmentParameter, AvailableSymbols ]
          TRIGGERED_CANDLESTICKS_QUEUE_URL: !Ref TriggeredCandlesticksQueue
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: !FindInMap [ EnvironmentMap, !Ref EnvironmentParameter, TriggerAllCandlesticksSchedule ]
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt TriggeredCandlesticksQueue.QueueName

  UpdateAllCandlesticksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Update all candlesticks function
      CodeUri: dist/webpack/update-all-candlesticks-handler
      Handler: app.handler
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Environment:
        Variables:
          EXCHANGES_SECRET_NAME: !Ref ExchangesSecretNameParameter
          CANDLESTICK_TABLE_NAME: !Ref CandlestickTable
          UPDATED_CANDLESTICKS_QUEUE_URL: !Ref UpdatedCandlesticksQueue
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt TriggeredCandlesticksQueue.Arn
            BatchSize: 5
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${ExchangesSecretNameParameter}*
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${ExchangesSecretEncryptionKeyParameter}
        - DynamoDBWritePolicy:
            TableName: !Ref CandlestickTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt UpdatedCandlesticksQueue.QueueName

  PublishAllActiveStrategiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Publish all active strategies function
      CodeUri: dist/webpack/publish-all-active-strategies-handler
      Handler: app.handler
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Environment:
        Variables:
          STRATEGY_TABLE_NAME: !Ref StrategyTable
          ACTIVE_STRATEGIES_QUEUE_URL: !Ref ActiveStrategiesQueue
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt UpdatedCandlesticksQueue.Arn
            BatchSize: 5
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref StrategyTable
        - SQSPollerPolicy:
            QueueName: !GetAtt UpdatedCandlesticksQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ActiveStrategiesQueue.QueueName

  EvaluateStrategyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Evaluate strategy function
      CodeUri: dist/webpack/evaluate-strategy-handler
      Handler: app.handler
      MemorySize: 1024
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Environment:
        Variables:
          EXCHANGES_SECRET_NAME: !Ref ExchangesSecretNameParameter
          CANDLESTICK_TABLE_NAME: !Ref CandlestickTable
          STRATEGY_TABLE_NAME: !Ref StrategyTable
          ORDER_TABLE_NAME: !Ref OrderTable
          PROCESSED_STRATEGY_STEP_QUEUE_URL: !Ref ProcessedStrategyStepQueue
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt ActiveStrategiesQueue.Arn
            BatchSize: 1
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${ExchangesSecretNameParameter}*
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${ExchangesSecretEncryptionKeyParameter}
        - DynamoDBReadPolicy:
            TableName: !Ref CandlestickTable
        - DynamoDBReadPolicy:
            TableName: !Ref StrategyTable
        - DynamoDBWritePolicy:
            TableName: !Ref StrategyTable
        - DynamoDBWritePolicy:
            TableName: !Ref OrderTable
        - SQSPollerPolicy:
            QueueName: !GetAtt ActiveStrategiesQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ProcessedStrategyStepQueue.QueueName

  ApiV1:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref EnvironmentParameter
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
          Quota:
            Period: DAY
            Limit: 500
          Throttle:
            RateLimit: 5
            BurstLimit: 5
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./api/openapi.yml

  GetAllCandlesticksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get all candlesticks function
      CodeUri: dist/webpack/get-all-candlesticks-handler
      Handler: app.handler
      MemorySize: 1024
      Environment:
        Variables:
          CANDLESTICK_TABLE_NAME: !Ref CandlestickTable
          AVAILABLE_SYMBOLS: !FindInMap [ EnvironmentMap, !Ref EnvironmentParameter, AvailableSymbols ]
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiV1
            Path: /candlesticks
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CandlestickTable

  CandlestickTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: true
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S

  StrategyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: symbolStatusPk
          AttributeType: S
        - AttributeName: symbolStatusSk
          AttributeType: S
        - AttributeName: stepsListPk
          AttributeType: S
        - AttributeName: stepsListSk
          AttributeType: N
      GlobalSecondaryIndexes:
        - IndexName: SymbolStatus-Index
          KeySchema:
            - AttributeName: symbolStatusPk
              KeyType: HASH
            - AttributeName: symbolStatusSk
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: StepsList-Index
          KeySchema:
            - AttributeName: stepsListPk
              KeyType: HASH
            - AttributeName: stepsListSk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S

  TriggeredCandlesticksQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      MessageRetentionPeriod: 60

  UpdatedCandlesticksQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      MessageRetentionPeriod: 60
      FifoQueue: true
      DeduplicationScope: messageGroup
      FifoThroughputLimit: perMessageGroupId

  ActiveStrategiesQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      MessageRetentionPeriod: 60
      FifoQueue: true
      DeduplicationScope: messageGroup
      FifoThroughputLimit: perMessageGroupId

  ProcessedStrategyStepQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      MessageRetentionPeriod: 60
      FifoQueue: true
      DeduplicationScope: messageGroup
      FifoThroughputLimit: perMessageGroupId

Outputs:
  InitializeAllCandlesticksFunctionName:
    Description: Initialize all candlesticks function name
    Value: !Ref InitializeAllCandlesticksFunction
  InitializeAllCandlesticksFunctionArn:
    Description: Initialize all candlesticks function name
    Value: !Ref InitializeAllCandlesticksFunction

  UpdateAllCandlesticksFunctionName:
    Description: Update all candlesticks function name
    Value: !Ref UpdateAllCandlesticksFunction
  UpdateAllCandlesticksFunctionArn:
    Description: Update all candlesticks function name
    Value: !Ref UpdateAllCandlesticksFunction

  PublishAllActiveStrategiesFunctionName:
    Description: Publish all active strategies function name
    Value: !Ref PublishAllActiveStrategiesFunction
  PublishAllActiveStrategiesFunctionArn:
    Description: Publish all active strategies function ARN
    Value: !GetAtt PublishAllActiveStrategiesFunction.Arn

  EvaluateStrategyFunctionName:
    Description: Evaluate strategy function name
    Value: !Ref EvaluateStrategyFunction
  EvaluateStrategyFunctionArn:
    Description: Evaluate strategy function ARN
    Value: !GetAtt EvaluateStrategyFunction.Arn

  ApiV1Id:
    Description: API v1 ID
    Value: !Ref ApiV1
  ApiV1Url:
    Description: API v1 URL
    Value: !Sub https://${ApiV1}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentParameter}/
  ApiV1RootResourceId:
    Description: API v1 root resource ID
    Value: !GetAtt ApiV1.RootResourceId

  GetAllCandlesticksFunctionName:
    Description: Get all candlesticks function name
    Value: !Ref GetAllCandlesticksFunction
  GetAllCandlesticksFunctionArn:
    Description: Get all candlesticks function ARN
    Value: !GetAtt GetAllCandlesticksFunction.Arn

  CandlestickTableName:
    Description: Candlestick table name
    Value: !Ref CandlestickTable
  CandlestickTableArn:
    Description: Candlestick table ARN
    Value: !GetAtt CandlestickTable.Arn

  StrategyTableName:
    Description: Strategy table name
    Value: !Ref StrategyTable
  StrategyTableArn:
    Description: Strategy table ARN
    Value: !GetAtt StrategyTable.Arn

  OrderTableName:
    Description: Order table name
    Value: !Ref OrderTable
  OrderTableArn:
    Description: Order table ARN
    Value: !GetAtt OrderTable.Arn

  TriggeredCandlesticksQueueName:
    Description: Triggered candlesticks queue name
    Value: !GetAtt TriggeredCandlesticksQueue.QueueName
  TriggeredCandlesticksQueueArn:
    Description: Triggered candlesticks queue ARN
    Value: !GetAtt TriggeredCandlesticksQueue.Arn
  TriggeredCandlesticksQueueUrl:
    Description: Triggered candlesticks queue URL
    Value: !Ref TriggeredCandlesticksQueue

  UpdatedCandlesticksQueueName:
    Description: Updated candlesticks queue name
    Value: !GetAtt UpdatedCandlesticksQueue.QueueName
  UpdatedCandlesticksQueueArn:
    Description: Updated candlesticks queue ARN
    Value: !GetAtt UpdatedCandlesticksQueue.Arn
  UpdatedCandlesticksQueueUrl:
    Description: Updated candlesticks queue URL
    Value: !Ref UpdatedCandlesticksQueue

  ActiveStrategiesQueueName:
    Description: Active strategies queue name
    Value: !GetAtt ActiveStrategiesQueue.QueueName
  ActiveStrategiesQueueArn:
    Description: Active strategies queue ARN
    Value: !GetAtt ActiveStrategiesQueue.Arn
  ActiveStrategiesQueueUrl:
    Description: Active strategies queue URL
    Value: !Ref ActiveStrategiesQueue

  ProcessedStrategyStepQueueName:
    Description: Processed strategy step queue name
    Value: !GetAtt ProcessedStrategyStepQueue.QueueName
  ProcessedStrategyStepQueueArn:
    Description: Processed strategy step queue ARN
    Value: !GetAtt ProcessedStrategyStepQueue.Arn
  ProcessedStrategyStepQueueUrl:
    Description: Processed strategy step queue URL
    Value: !Ref ProcessedStrategyStepQueue
